ARG DOTNET_ASPNET_IMAGE=mcr.microsoft.com/dotnet/aspnet:10.0
FROM ${DOTNET_ASPNET_IMAGE} AS runtime

WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_RUNNING_IN_CONTAINER=true

EXPOSE 8080

ARG PUBLISH_DIR=artifacts/docker/publish
COPY ${PUBLISH_DIR}/ ./

ENTRYPOINT ["dotnet", "ByteBite.Api.dll"]
